# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "gitmodules"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/utils/dockerbuilds/mingw/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/utils/dockerbuilds/msys2/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/utils/dockerbuilds/steamrt/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/utils/wesnoth-map-diff/"
    schedule:
      interval: "weekly"
